Repository kod3rsStore/Backend, pull requests merged in 2020-05, with the labels that each got.

#2 Starts project
  .env
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/server.js
Labels: Backend API

#4 [update] untracked .env file
  .env
  .gitignore
  src/config/index.js
  src/server.js
Labels: Backend API

#6 Create server
  network/response.js
  package-lock.json
  package.json
  src/config/index.js
  src/routes/users/controller.js
  src/routes/users/index.js
  src/routes/users/network.js
  src/server.js
  src/store/mysql.js
Labels: Backend API

#19 Created the readme file
  README.md
Labels: Backend API

#21 14-create addresses endpoint
  src/routes/addresses/controller.js
  src/routes/addresses/index.js
  src/routes/addresses/network.js
  src/server.js
Labels: Backend API

#23 15-Create shopping cart endpoint
  src/routes/shopping_carts/controller.js
  src/routes/shopping_carts/index.js
  src/routes/shopping_carts/network.js
  src/server.js
  src/store/mysql.js
Labels: Backend API

#24 17- test starter
  package-lock.json
  package.json
  src/routes/shopping_carts/network.js
  src/server.js
  tests/mock.json
  tests/test.js
Labels: Backend API

#27 25-Swagger documentation ui endpoint
  api_doc/swagger.js
  api_doc/swagger.json
  package-lock.json
  package.json
  src/routes/addresses/controller.js
  src/routes/products/controller.js
  src/routes/shopping_carts/network.js
  src/routes/users/controller.js
  src/server.js
Labels: Backend API

#29 create the seed files
  .env.example
  package-lock.json
  package.json
  scripts/database/kod3rsStore.sql
  scripts/mocks/albums.js
  scripts/mocks/categories.js
  scripts/mocks/cities_catalog.js
  scripts/mocks/countries_catalog.js
  scripts/mocks/currencies.js
  scripts/mocks/directions.js
  scripts/mocks/module_access.js
  scripts/mocks/product_photos.js
  scripts/mocks/products.js
  scripts/mocks/security_levels.js
  scripts/mocks/states.js
  scripts/mocks/users.js
  scripts/mysql/seedDatabase.js
  src/config/index.js
Labels: Backend API

#32 Data validation
  .env.example
  package-lock.json
  package.json
  src/config/index.js
  src/routes/addresses/network.js
  src/routes/categories/network.js
  src/routes/login/controller.js
  src/routes/login/index.js
  src/routes/login/network.js
  src/routes/products/controller.js
  src/routes/products/network.js
  src/routes/shopping_carts/network.js
  src/routes/users/network.js
  src/server.js
  src/utils/middleware/validationHandler.js
  src/utils/schemas/addresses.js
  src/utils/schemas/categories.js
  src/utils/schemas/login.js
  src/utils/schemas/products.js
  src/utils/schemas/shopping_carts.js
  src/utils/schemas/users.js
Labels: Backend API

#35 configure passportJS at backend
  package-lock.json
  package.json
  src/routes/auth/controller.js
  src/routes/auth/index.js
  src/routes/auth/network.js
  src/routes/users/controller.js
  src/server.js
  src/utils/auth/strategies/basic.js
  src/utils/auth/strategies/jwt.js
Labels: Backend API

#44 created scopes and validations
  scripts/database/kod3rsStore24052020.sql
  scripts/mocks/categories.js
  scripts/mocks/directions.js
  scripts/mocks/products.js
  src/routes/addresses/network.js
  src/routes/auth/index.js
  src/routes/auth/network.js
  src/routes/categories/network.js
  src/routes/products/network.js
  src/routes/shopping_carts/network.js
  src/routes/users/controller.js
  src/routes/users/network.js
  src/utils/auth/strategies/basic.js
  src/utils/auth/strategies/jwt.js
  src/utils/middleware/scopesValidationHandler.js
Labels: Backend API

#46 configure google authentication
  src/routes/auth/controller.js
  src/routes/auth/network.js
  src/routes/users/controller.js
  src/utils/schemas/users.js
Labels: Backend API

#49 create scopes endpoint
  package.json
  src/routes/login/controller.js
  src/routes/login/index.js
  src/routes/login/network.js
  src/routes/scopes/controller.js
  src/routes/scopes/index.js
  src/routes/scopes/network.js
  src/server.js
  src/utils/middleware/scopesValidationHandler.js
  src/utils/schemas/scopes.js
Labels: Backend API

#50 Add gitlab-ci file to the project
  .gitlab-ci.yml
  package.json
Labels: Backend API, CI / CD

#54 53-upload pictures
  .gitignore
  package-lock.json
  package.json
  src/routes/addresses/network.js
  src/routes/categories/network.js
  src/routes/products/controller.js
  src/routes/products/network.js
  src/routes/shopping_carts/network.js
  src/routes/users/controller.js
  src/routes/users/network.js
  src/server.js
  src/utils/schemas/products.js
  src/utils/schemas/users.js
Labels: Backend API

#56 added security layer to the CI process
  .gitlab-ci.yml
Labels: CI / CD

#57 fixed gitlab-ci-yml bugs
  .gitlab-ci.yml
Labels: CI / CD

#59 fixed some bugs
  .gitlab-ci.yml
Labels: CI / CD

#61 add code quality to the test CI
  .gitlab-ci.yml
Labels: CI / CD

#63 fixed the gitlab-ci.yml
  .gitlab-ci.yml
Labels: CI / CD

#65 fixed some bugs
  .gitlab-ci.yml
Labels: CI / CD

#67 fixed some bugs
  .gitlab-ci.yml
Labels: CI / CD

#69 Removed DAST configuration from gitlab-ci.yml
  .gitlab-ci.yml
Labels: CI / CD

#77 42-paypal payment
  .gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/config/index.js
  backend/src/routes/paypal/controller.js
  backend/src/routes/paypal/network.js
  backend/src/server.js
  backend/tests/mockup.json
  package-lock.json
Labels: Backend API

#78 changed docker compose configuration
  .dockerignore
  backend/dockerfile
  backend/src/config/index.js
  backend/src/routes/users/network.js
  backend/src/server.js
  docker-compose.yml
Labels: CI / CD

#80 Add viz to docker
  .gitlab-ci.yml
  backend/.env.example
  backend/dockerfile
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
Labels: CI / CD

#81 fix the docker-compose file
  backend/Dockerfile
  docker-compose.prod.yml
Labels: CI / CD

#82 fix-docker-compose
  docker-compose.prod.yml
Labels: CI / CD

#84 removed the viz app from the docker-compose
  docker-compose.dev.yml
  docker-compose.prod.yml
Labels: CI / CD

#85 modified docker-compose
  docker-compose.dev.yml
  docker-compose.prod.yml
  package-lock.json
Labels: CI / CD

#88 dockerfile modified
  backend/Dockerfile
  backend/package.json
Labels: CI / CD

#92 added an initial access
  backend/src/routes/initial/network.js
  backend/src/server.js
Labels: Backend API

#94 create stripe payment endpoint
  backend/package-lock.json
  backend/package.json
  backend/src/config/index.js
  backend/src/routes/stripe/controller.js
  backend/src/routes/stripe/index.js
  backend/src/routes/stripe/network.js
  backend/src/server.js
Labels: Backend API

#97 added the products search endpoints
  backend/scripts/database/kod3rsStore.sql
Labels: Backend API
